### ISSUE TITLE
Patch adding proper Makefile

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eddieantonio/isri-ocr-evaluation-tools#1]
```
The current build system sucks a lot. Indeed the current README states "A more 
featureful and flexible build procedure will hopefully come in the future."

This patch is that future. It replaces all the 'Build' shell scripts with one 
robust, simple, correct Makefile, which includes an "install" rule. It also 
fixes a couple of tiny build bugs in a couple of C files.
```

Original issue reported on code.google.com by `nick.wh...@durham.ac.uk` on 22 Feb 2013 at 5:09

Attachments:
* [add-makefile.patch](https://storage.googleapis.com/google-code-attachments/isri-ocr-evaluation-tools/issue-1/comment-0/add-makefile.patch)

**Comment by eddieantonio** [comment]
Implemented as of d823464e620dac20ff2967f369b7a6b8a7759626.
