### ISSUE TITLE
Including results for letters ä ö and å for final report possible?

### ISSUE THREAD

**Issue by jmokoistinen** [eddieantonio/isri-ocr-evaluation-tools#14]
Hi again

Any idea how to include character accuracies for specific characters äöå and ÄÖÅ to the reports?
Tried to look through the codes and seems the characters are defined in src/charclass.c, but no idea where they should be selected to the final results?
The accsum does not take these letters into the listing at the bottom, even there are those in the summed lists.

Thanks!

**Comment by eddieantonio** [comment]
Hey Mika,

Could you send me some sample input? I can't seem to replicate this or I don't exactly understand what is missing from the output. I tried the following with release 6.1.1:

 1. copy-paste first paragraph from [Finnish Wikipedia article on OCR](https://fi.wikipedia.org/wiki/Tekstintunnistus) to a file called `correctfile`. [NFC normalize it](http://www.macchiato.com/unicode/nfc-faq) such that ä, ö, å are always represented by one Unicode code point/scalar value (does not work with any arbitrary combination of accents!)
 2. copy `correctfile` to `generatedfile` and change some "ä" to "a" and some "ö" to "o".
 3.
    ```sh
     $ ./bin/accuracy correctfile generatedfile report-1
     $ ./bin/accuracy correctfile generatedfile report-2
    ```
4. 
    ```sh
     $ ./bin/accsum report-1 report-2
    UNLV-ISRI OCR Accuracy Report Version 6.1
    -----------------------------------------
        1124   Characters
           8   Errors
       99.29%  Accuracy
    
           0   Reject Characters
           0   Suspect Markers
           0   False Marks
        0.00%  Characters Marked
       99.29%  Accuracy After Correction
    
         Ins    Subst      Del   Errors
           0        0        0        0   Marked
           0        6        2        8   Unmarked
           0        6        2        8   Total
    
       Count   Missed   %Right
         112        0   100.00   ASCII Spacing Characters
          62        0   100.00   ASCII Special Symbols
          42        0   100.00   ASCII Uppercase Letters
         908        6    99.34   ASCII Lowercase Letters
        1124        6    99.47   Total
    
      Errors   Marked   Correct-Generated
           4        0   {ä}-{a}
           2        0   {}-{<\n>}
           2        0   {ö}-{o}
    
       Count   Missed   %Right
         112        0   100.00   { }
          20        0   100.00   {"}
           8        0   100.00   {(}
           8        0   100.00   {)}
          16        0   100.00   {,}
           2        0   100.00   {-}
           8        0   100.00   {.}
           8        0   100.00   {C}
           4        0   100.00   {I}
           4        0   100.00   {M}
          10        0   100.00   {O}
          12        0   100.00   {R}
           4        0   100.00   {T}
         104        0   100.00   {a}
          16        0   100.00   {c}
           4        0   100.00   {d}
          82        0   100.00   {e}
          12        0   100.00   {g}
          10        0   100.00   {h}
         116        0   100.00   {i}
          12        0   100.00   {j}
          42        0   100.00   {k}
          54        0   100.00   {l}
          20        0   100.00   {m}
          66        0   100.00   {n}
          48        0   100.00   {o}
          14        0   100.00   {p}
          30        0   100.00   {r}
          94        0   100.00   {s}
          98        0   100.00   {t}
          36        0   100.00   {u}
          14        0   100.00   {v}
           6        0   100.00   {w}
          30        6    80.00   {y}
    ```

**Comment by eddieantonio** [comment]
Update: The bug is in [accrpt.c](https://github.com/eddieantonio/isri-ocr-evaluation-tools/blob/v6.1.1/src/accrpt.c#L160):

```c
            while (read_two(f, &value1, &value2))
            {
                if (line[CLASS_OFFSET + 2] == '}')
                    value3 = line[CLASS_OFFSET + 1];
                else if (line[CLASS_OFFSET + 2] == '\\')
                    value3 = NEWLINE;
                else
                    sscanf(&line[CLASS_OFFSET + 2], "%lx", &value3);
                add_class(accdata, value3, value1, value2);
            }
```

This code reads in the very end of the accuracy report, but it assumes a **single-byte character encoding**. I introduced this bug when I changed the display of characters in the accuracy report such that printable UTF-8 characters would actually show up as UTF-8 characters. The original code only handled Latin-1, or 16-bit Unicode in a special 8-bit encoding. I'll see what I can do to fix it.

**Comment by jmokoistinen** [comment]
Hi Eddie

Yes the lower list after accsum does not have äöåÄÅÖ counts, missed,
right%. eventhough the separate lists have.

I can send example next week after Xmas holidays,  if still necessary? Does
it replicate if you change ä to the lower list(s) before accsum and then
run accsum?

Br,  Mika

**Comment by eddieantonio** [comment]
It's simply a bug with how accsum reads in accuracy reports, regardless of order or characters. I probably won't need sample input, but it would be helpful if we still haven't got it resolved by then! Again, thanks for discovering this bug!

**Comment by eddieantonio** [comment]
Hey @jmokoistinen,

v6.1.2 should have fixed this. The bottom list given by accsum should have any non-ASCII character, including ä, ö, å, etc.

Let me know if there still any problems, and thanks for reporting issues!
