### ISSUE TITLE
word accuracy output is not recognized as khmer words but in clusters

### ISSUE THREAD

**Issue by phyrumsk** [eddieantonio/isri-ocr-evaluation-tools#17]
I tested "wordacc correct_file  tesseract_4.0_generated_file"  for khmer language.
In UNLV-ISRI OCR Word Accuracy Report Version 6.1, I found out that
- Total number of khmer clusters are counted as total number of words in report
 - Non-stopwords result works fine for English language as it segments correct word but in Khmer language it segments clusters not words. I also attached my output of wordacc report as reference.

Is there anyway or any parameter should I specify in ISRI wordacc tool to produce correct word accuracy report for Khmer language?

Best regards,
Phyrum

[wordacc_khmeros_oem_1.txt](https://github.com/eddieantonio/isri-ocr-evaluation-tools/files/1336305/wordacc_khmeros_oem_1.txt)

**Comment by eddieantonio** [comment]
Hi Phyrum,

Unfortunately, the current version uses a generic word segmentation method ([UAX #29](http://unicode.org/reports/tr29/#Word_Boundaries)), which really only works for languages in Latin script. In fact, the specification states:

> For Thai, Lao, Khmer, Myanmar, and other scripts that do not typically use spaces between words, **a good implementation should not depend on the default word boundary specification**. It should use a more sophisticated mechanism, as is also required for line breaking.

There is no option to use a more sophisticated method for Khmer. If there is a feasible way to include this as a feature, I'll look into it. [Here's a site that talks about Khmer word segmentation](http://blog.khmerocr.com/p/khmer-tools.html).

**Comment by phyrumsk** [comment]
Thanks for your explanation.
