### ISSUE TITLE
accuracy: invalid UTF-8 character

### ISSUE THREAD

**Issue by VijayalakshmiSundaravaradhan** [eddieantonio/isri-ocr-evaluation-tools#18]

**Comment by eddieantonio** [comment]
Hello! Please help me by providing more context so I can debug this. I will need:

 - a sample text file that will cause this bug
 - how you invoked `accuracy` (what did you type on the command line?)
 - what OS you're on (mac/windows/linux?)

Thanks!

**Comment by eddieantonio** [comment]
Hey @VijayalakshmiSundaravaradhan,

Without any context for the issue, my best guess is that this message is triggered by code that checks whether its input is a valid UTF-8 encoded file. This probably means that the file was **not** encoded in UTF-8, but rather, some other file encoding. `accuracy` only handles ASCII and UTF-8 encoded files, so if your text files are in a different encoding, you must convert them first.

To convert file encodings, you can either use the `Save as...` feature in most text editors, or use `iconv`:

    iconv -f latin1  -t UTF-8 my-file.txt > my-file-utf-8.txt  # convert from Latin-1
    iconv -f CP1251  -t UTF-8 my-file.txt > my-file-utf-8.txt  # convert from Windows 1251
    iconv -f SHIFT-JIS -t UTF-8 my-file.txt > my-file-utf-8.txt  # convert from Shift-JIS

I hope this helps! If you think this really is a bug with the OCR tools, please send additional contex as mentioned in my previous comment and feel free to reopen this issue!
