### ISSUE TITLE
Wrapper script to use tools with UTF-8 input files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eddieantonio/isri-ocr-evaluation-tools#2]
```
Attached is a wrapper script to make the tools here run correctly with UTF-8. 
Of course it would be much better to make them use UTF-8 internally directly, 
but that's quite a big job, and this script works perfectly well.

Use it like this:

  utf8toolwrap.sh accuracy ground.txt ocr.txt # run the 'accuracy' tool

It probably isn't needed for tools like accsum that just postprocess the output 
from the real tests, but certainly 'accuracy', the most important, is suddenly 
useful with it!
```

Original issue reported on code.google.com by `nick.wh...@durham.ac.uk` on 23 Feb 2013 at 11:12

**Comment by eddieantonio** [comment]
Alternatively, use [extended_ascii](https://github.com/eddieantonio/isri-extended-ascii) as a pipe filter for files!

**Comment by eddieantonio** [comment]
As of 60f4a92 (v6.0.0-rc.1), the tools read and write exclusively in UTF-8. No conversion necessary! Making all the tools Unicode aware is still a work in progress...

**Comment by eddieantonio** [comment]
Obsolete as of v6.0.0 (1ec3325)

**Comment by amitdo** [comment]
Pinging @nickjwhite, the original (googlecode) issue submitter.
