### ISSUE TITLE
[Suggestion] Directories reorder and renaming

### ISSUE THREAD

**Issue by amitdo** [eddieantonio/isri-ocr-evaluation-tools#4]
Hello!

Nice work :-)

My suggestions:
* Rename 'Modules' to 'Lib'.
* Create a new folder named 'Progs' and move all the utilities (accci, accdist, accsum, etc.) to this folder.
* Create a new folder named 'Man' and move all the manpages to there.
* Create a new folder named 'src' and move 'Lib' and 'Progs' (and others) to there.

**Comment by eddieantonio** [comment]
@amitdo Hey, thanks!

I left these folders with the same structure because I really only ported the old code written in 1996 by Stephen Rice to modern computers, and added UTF-8 support. The only thing I did in terms of structure is everything in `analytic-tools` to the root directory.

Why would you suggest these changes?

**Comment by amitdo** [comment]
Hi again!

I reviewed your commits, so I know what changes you made so far.

> Why would you suggest these changes?

Well, It's a matter of style. Many open source projects have a directory layout that include 'src' and/or 'lib' dirs. Some projects use 'prog(s)' dir, but it's less common.

https://github.com/kriasoft/Folder-Structure-Conventions
https://github.com/DanBloomberg/leptonica

It's just a suggestion, feel free to not accept it... :)

BTW, a few years ago I started rewriting this project in Python. Never finished it...

**Comment by amitdo** [comment]
FYI, I added a link to this project to Tesseract wiki:
https://github.com/tesseract-ocr/tesseract/wiki/3rdParty

I hope this is ok with you.

**Comment by eddieantonio** [comment]
Heya!

Sorry if I sounded offended in my last post; I have a conference submission deadline looming _and_  a major assignment due soon, so adding more potential work for me right now is like :tired_face:

That said! This is a good idea! :smile: However, I like a more unix-y structure a bit better:

```
.
├── bin                 # Compiled binaries of utilities
├── include             # Public C/C++ API (does not really exist yet...)
├── lib
│   └── libisri.a       # Used for internal linking
│   └── libisri.so.60   # Used for dynamically linking with external applications
├── libexec             # Scripts used internally
├── man
│   └── man1            # Man pages for each binary
│   └── man3            # Man pages for public API?
├── src                 # Source of libisri and binaries
└── test                # Tests
```

This way, developers on Unix-y systems can simply add each directory to their respective paths:

```sh
ISRI=$HOME/isri-ocr-evaluation-tools # or wherever you decide to put this repo
export PATH=$ISRI/bin:$PATH
export MANDIR=$ISRI/man:$MANPATH
export LD_LIBRARY_PATH=$ISRI/lib:$LD_LIBRARY_PATH
```

I've suggested a public API, which may be _a lot_ of work, but if implemented, you could link with ISRI libs like so:

```sh
g++ \
    -I$HOME/isri-ocr-evaluation-tools/include \ # Typically set in CPPFLAGS in a Makefile
    -L$HOME/isri-ocr-evaluation-tools/lib     \ # Typically set in LDFLAGS in a Makefile
    mycoolocrthing.cc -o mycoolocrthing       \ 
    -lisri                                      # Link with ISRI OCR evaluation tools
```

**Comment by amitdo** [comment]
:+1:

But do it only if/when your have enough free time. :)
